### ISSUE TITLE
10000 вынести в константу

### ISSUE THREAD

**Issue by coursar** [andruhanishe/DZ_04_Bonus#6]
https://github.com/andruhanishe/DZ_04_Bonus/blob/59b0e498a8a6ae33078c693987b486f1776f1282/src/js/lib.js#L5-L6

**Comment by andruhanishe** [comment]
Добавил параметр для 10000 в функцию
https://github.com/andruhanishe/DZ_04_Bonus/blob/bd99badb8674518e21145c3d6b6439c028c42a73/src/js/lib.js#L1-L6

**Comment by coursar** [comment]
Если сделали - закрывайте
